### KNN 분류(Classification)
- 새로운 값은 기존 데이터를 기존으로 가장 가까운 k개의 최근접 값을 기준으로 분류됨
- k는 동률의 문제 때문에 짝수는 되도록 피하는 것이 좋음
- k가 1에 가까울 수록 과적합, k가 클수록 과소적합이 되기 때문에 적절한 k값 선정이 필요


### KNN 회귀(Regression)
- 기본 개념은 분류 모델과 같으며, k개의 인접한 자료의 (가중)평균으로 예측

#### sklearn-KNeighborsClassifier() / Regressor()

In [2]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

In [3]:
df = pd.read_csv("C:/Users/Data/iris.csv")

In [4]:
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [5]:
df['is_setosa'] = (df['Species'] == 'setosa') + 0

In [6]:
model_c = KNeighborsClassifier(n_neighbors=3)

In [8]:
model_c.fit(X = df.iloc[:, :4], y = df['is_setosa'])
model_c

KNeighborsClassifier(n_neighbors=3)

In [9]:
model_c.predict(df.iloc[:, :4])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true = df['is_setosa'],
              y_pred = model_c.predict(df.iloc[:, :4]))

1.0

In [12]:
model_r = KNeighborsRegressor(n_neighbors=3)
model_r.fit(X = df.iloc[:, :3],
           y = df["Petal.Width"])
model_r

KNeighborsRegressor(n_neighbors=3)

In [13]:
pred_r = model_r.predict(df.iloc[:, :3])
pred_r[:5]

array([0.26666667, 0.2       , 0.16666667, 0.2       , 0.16666667])

In [14]:
from sklearn.metrics import mean_squared_error as mse

In [16]:
mse(y_true = df["Petal.Width"],
   y_pred = pred_r) ** 0.5 # 루트 씌우기

0.13654466098842696

In [17]:
df = pd.read_csv("C:/Users/Data/diabetes.csv")

In [18]:
df.head(4)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0

In [49]:
from sklearn.model_selection import train_test_split

df['is_preg'] = (df['Pregnancies'] > 0) + 0
df_train, df_test = train_test_split(df, test_size=0.3, random_state=123)

In [50]:
model = KNeighborsClassifier()
model.fit(X = df_train.loc[:, ['Pregnancies', 'Glucose', 'BloodPressure']],
                              y = df_train['Outcome'])
pred = model.predict(df_test.loc[:, ['Pregnancies', 'Glucose', 'BloodPressure']])
pred[:5]

array([1, 0, 0, 0, 0], dtype=int64)

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
accuracy_score(y_pred = pred,
              y_true = df_test['Outcome'])

0.7272727272727273

In [62]:
import numpy as np

df_train, df_test = train_test_split(df, test_size=0.2, random_state=123)

X_cols = ['is_preg', 'Glucose', 'BloodPressure', 'Insulin', 'BMI']

nums = [3, 5, 10, 20]
accs = []

for i in nums:
    model = KNeighborsClassifier(n_neighbors = i)
    model.fit(X = df_train.loc[:, X_cols], y = df_train['Outcome'])
    pred = model.predict(df_test.loc[:, X_cols])
    acc_sub = accuracy_score(y_pred = pred, y_true = df_test['Outcome'])
    accs += acc_sub
    
df_score = pd.DatFrame({"neighbors": nums, "accs" : accs})
df_score['accs'] = df_score['accs'].round(2)
df_score # TypeError: 'numpy.float64' object is not callable

TypeError: 'numpy.float64' object is not callable

In [60]:
import numpy as np

#define arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([12, 14, 14, 19, 22])

#multiply two arrays together
combo = (x)*(y)

#view result
print(combo)

[ 12  28  42  76 110]
